apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: productcatalogservice
  namespace: product-catalog
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - external:
      metric:
       name: istio.io|service|server|request_count
       selector:
         matchLabels:
           resource.labels.canonical_service_name: productcatalogservice
      target:
        type: AverageValue
        averageValue: 8
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productcatalogservice
