apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: productcatalogservice
  namespace: product-catalog
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: productcatalogservice
